# Generated by Django 5.2.1 on 2025-06-06 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_remove_produto_categoria_produto_subcategoria'),
        ('payments', '0002_remove_payment_amount_remove_payment_tx_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='private_key',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_brl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='initial_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Store.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
