# Generated by Django 5.2.1 on 2025-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_remove_produto_categoria_produto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
