# Generated by Django 5.2.1 on 2025-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_profile_mp_access_token_profile_mp_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
